name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0/2 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: True
          SHOW_TITLE: True
          TIME_RANGE: last_30_days
          SHOW_TOTAL: True
          SHOW_LANGUAGE: True
          SHOW_TIMEZONE: True
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_LOC_CHART: False
          
